# ---
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - main: ./cmd/daydeal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: mhutter
    name: homebrew-tap
  homepage: 'https://github.com/mhutter/daydeal'
  description: CLI tool to fetch the current DayDeal
  test: |
    system "#{bin}/daydeal"
