---
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go version
      - run:
          name: "Fetch dependencies"
          command: go mod download
      # Only run gofmt, vet & lint against the latest Go version
      - run:
          name: "Run gofmt"
          command: |
            if [[ "$CIRCLE_JOB" = "latest" ]]; then
              diff -u <(echo -n) <(gofmt -d -e .)
            fi
      - run:
          name: "Run go vet"
          command: |
            if [[ "$CIRCLE_JOB" = "latest" ]]; then
              go vet ./...
            fi
      - run:
          name: "Run golint"
          command: |
            if [ "$CIRCLE_JOB" = "latest" ] && [ -z "$SKIP_GOLINT" ]; then
              go get golang.org/x/lint/golint
              golint ./...
            fi
      - run:
          name: "Run staticcheck"
          command: |
            if [ "$CIRCLE_JOB" = "latest" ] && [ -z "$SKIP_STATICCHECK" ]; then
              go get honnef.co/go/tools/cmd/staticcheck
              staticcheck ./...
            fi
      - run: make test

  release:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test-release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
